const defaultPaperInfos = [
  {
    id: "1",
    author: "Liang Fu C.",
    title: "Kane Proxity effect of s wave superconductor",
    year: 2007,
    journal: "Physical Review Letters",
    tags: ["topological insulator", "superconductor", "proximity effect"],
    citations: ["3"],
    citedBy: [],
  },
  // {
  //   id: "2",
  //   author: "Hoge Hoge.",
  //   title: "hoge hoge",
  //   year: 2023,
  //   journal: "Hoge Hoge Journal",
  //   tags: ["hoge", "fuga"],
  //   citations: ["3", "11"],
  //   citedBy: ["1"],
  // },
  // {
  //   id: "3",
  //   author: "Piyo Piyo.",
  //   title: "piyo piyo",
  //   year: 2003,
  //   journal: "PIyo Piyo Journal",
  //   tags: ["hoge", "piyo"],
  //   citations: [],
  //   citedBy: ["1", "2"],
  // },
  // {
  //   id: "4",
  //   author: "Fu Liang",
  //   title:
  //     "Superconducting Proximity Effect and Majorana Fermions at the Surface of a Topological Insulator",
  //   journal: "PRL",
  //   year: 2008,
  //   tags: ["hoge", "piyo"],
  //   citations: [],
  //   citedBy: ["1", "2"],
  // },
  // {
  //   id: "5",
  //   author: "piyo",
  //   title: "Superconductor",
  //   journal: "Phys. Rev. B",
  //   year: 2023,
  //   tags: ["superconductor"],
  //   citations: ["3", "4"],
  //   citedBy: [],
  // },
  // {
  //   id: "6",
  //   author: "hogeho",
  //   title: "The difference between grid and flexbox",
  //   journal: "Science",
  //   year: 2020,
  //   tags: ["flexbox"],
  //   citations: ["3"],
  //   citedBy: [],
  // },
  // {
  //   id: "7",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["1", "3", "4"],
  //   citedBy: [],
  // },
  // {
  //   id: "8",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["4", "3"],
  //   citedBy: [],
  // },
  // {
  //   id: "9",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["4"],
  //   citedBy: [],
  // },
  // {
  //   id: "10",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["4"],
  //   citedBy: [],
  // },
  // {
  //   id: "11",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["4"],
  //   citedBy: [],
  // },
  // {
  //   id: "12",
  //   author: "hogehoge",
  //   title: "How to use git",
  //   journal: "Nature",
  //   year: 2020,
  //   tags: ["commit"],
  //   citations: ["4"],
  //   citedBy: [],
  // },
];

export default defaultPaperInfos;
