on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run type-check
        working-directory: web
      # - run: npm ci && npm run type-check
      #   working-directory: functions
      - run: npm ci && npm run lint
